import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { TurnkeyProvider } from '@turnkey/sdk-react';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TurnkeyProvider
          config={{
            rpId: 'localhost',
            apiBaseUrl: 'https://api.turnkey.com',
            defaultOrganizationId:
              process.env.NEXT_PUBLIC_TURNKEY_ORGANIZATION_ID!,
          }}
        >
          <div className="min-h-screen flex flex-col items-center justify-center bg-gray-50">
            {children}
          </div>
        </TurnkeyProvider>
      </body>
    </html>
  );
}
